### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by josketres** [cotto16/domino#1]
All classes make perfectly sense to me (from an object oriented design perspective). 👍 nice job!

The only thing that I don't like is that the `score` is managed by the `Player` class. I don't think that it should be the responsibility of the `Player` to keep track of the score of the game. I would suggest moving that responsibility to the `Game` class. 

**Some other minor suggestions:**
* Add a [.gitignore](https://git-scm.com/docs/gitignore) and exclude `*.class`, `*.bluej` and `*.ctxt` files as they are not part of the source-code. As you already checked them in you'll have to remove them and commit the change.
* The class Domino is immutable, so you can make the fields final 
```java
class Domino {
   private final int left, right;
...
}
```
* The [Game#run](https://github.com/cotto16/domino/blob/master/Domino/Game.java#L24) method is too long. I suggest extracting the body of the `while` loop to an own method. Something like `playNextTurn`. This would make the code easier to read:
```java

   private final int left, right;
    public void run()
    {
        initialise();
        while(!isEnd())
        {
           playNextTurn();
        }
        end();
    }
}
```

**Comment by cotto16** [comment]
`score` is managed by the `Player` because it needs to know the dominos of the player. Dont know how to change this.
